# Generated by Django 5.2.5 on 2025-08-16 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(help_text='Введите содержание заметки', validators=[django.core.validators.MaxLengthValidator(10000)], verbose_name='Содержание'),
        ),
    ]
